build:
    environment:
        php: 7.3
        mysql: 5.7
        node: 10.15.3

    services:
        mysql: 5.7

    dependencies:
        before:
            - cp tests/.env.scrutinizer .env
            - mysql -e 'create database `scrutinizer`;'
            - mysql -e 'create database `tb-dev-testing`;'
            - composer self-update
            - composer install --no-interaction
            - pear install pear/PHP_CodeSniffer
            - phpenv rehash
            - npm install n -g
            - npm install -g jshint
            - npm install
        after:
            - php artisan key:generate
            - php artisan migrate

filter:
    excluded_paths:
        - 'tests/'
        - 'docs/'
        - 'vendor/'
        - 'node_modules'

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
