# build:
#     nodes:
#         analysis:
#             environment:
#                 php: 7.3
#                 mysql: 5.7
#                 node: 10.15.3
#                 # apache2:
#                 #     modules: ['rewrite']
#                 #     sites:
#                 #         symfony_app:
#                 #             web_root: 'web/'
#                 #             host: 'local.dev'
#                             # rules:
#                             #     - 'RewriteCond %{HTTP_REFERER} !^$'
#                             #     - 'RewriteCond %{HTTP_REFERER} !^http://(www.)?example.com/ [NC]'
#                             #     - 'RewriteRule .(gif|jpg|png)$ - [F]'
#             services:
#                 mysql: 5.7
#             tests:
#                 override:
#                     - php-scrutinizer-run  #  --enable-security-analysis
#             dependencies:
#                 before:
#                     - cp tests/.env.scrutinizer .env
#                     - mysql -e 'create database `scrutinizer`;'
#                     - composer install --no-interaction
#                     - npm install
#                     - php artisan key:generate
#                     - npm run production
# filter:
#     excluded_paths:
#         - 'tests/'
#         - 'docs/'
#         - 'storage/'
#     dependency_paths:
#         - 'vendor/'
#         - 'node_modules/'
tools:
    external_code_coverage:
        timeout: 900
        runs: 2
