build:
    environment:
        php: 7.2
        mysql: 5.7

    services:
        mysql: 5.7
    
    dependencies:
        before:
            - cp tests/.env.scrutinizer .env
            - mysql -e 'create database scrutinizer;'
            - mysql -e 'create database `tb-dev-testing`;'
            
            - composer self-update
            - composer install --no-interaction
            - pear install pear/PHP_CodeSniffer
            - phpenv rehash
            - npm install npm@latest -g
            - npm install -g jshint
            - npm install yarn
            - npm install
            - yarn import
        after:
            - php artisan key:generate
            - php artisan migrate
            