language: php
 env:
  global:
    - setup=stable
 matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=lowest
    - php: 7.2
      env: setup=lowest
 sudo: false
 cache:
  directories:
    - $HOME/.composer/cache
 services:
    - memcached
    - redis-server
    - mysql
 before_install:
    - mysql -e 'create database forge;'
    - mysql -e 'create user forge@localhost; grant all privileges on *.* to forge@localhost with grant option;'
    
before_script:
    - cp tests/.env.travis .env
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate
 install:
    - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
 script: 
    - vendor/bin/phpunit
    