language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=lowest
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
    - memcached
    - redis-server
    - mysql

before_install:
    - mysql -e 'create database tech_bench;'
#    - mysql -e 'create user forge@localhost; grant all privileges on *.* to forge@localhost with grant option;'
    
before_script:
    - cp tests/.env.travis .env
    
    - composer self-update
    - composer install --no-interaction
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash
#    - nvm install 7.7.1
    - npm install npm@latest -g
    - npm install -g jshint
    - npm install
    - php artisan key:generate
    - php artisan migrate

script: 
    - vendor/bin/phpunit
    - npm run production
    - jshint resources/assets/js/modules/*
