#################################################################################################################
#                                                                                                               #
#                                                                                                               #
#                                      Tech Bench Docker Installation                                           #
#         NOTE:  Modify .env file to change default passwords before executing `docker-compose up` command      #
#                                                                                                               #
#                                                                                                               #
#################################################################################################################
networks:
    app-tier:
        driver: bridge
volumes:
    assetData:
    keystore:

services:
    # Application Container
    tech_bench:
        container_name: tech_bench
        restart: unless-stopped
        image: butcherman/tech_bench_app:dev7
        volumes:
            - assetData:/app/public
            - keystore:/app/keystore
            - ./storageData/disks:/app/storage/app/
            - ./storageData/logs/app:/app/storage/logs
            - ./.env:/app/.env
        environment:
            - SERVICE=app
            - TB_URL=${BASE_URL}
        networks:
            - app-tier

    # NGINX Web Server
    nginx:
        image: butcherman/tech_bench_nginx:1.0
        container_name: nginx
        restart: unless-stopped
        volumes:
            - assetData:/app/public:ro
            - keystore:/app/keystore
            - ./storageData/logs/nginx:/app/storage/logs/nginx
        environment:
            - TB_URL=${BASE_URL}
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-tier

    # MySQL Database Container
    database:
        image: butcherman/tech_bench_database:1.0
        container_name: database
        restart: unless-stopped
        volumes:
            - ./appData/database:/bitnami/mysql/data
        networks:
            - app-tier
        environment:
            - MYSQL_ROOT_PASSWORD=tbRootPasswd

    #  Redis Container for Cache, Job and Email Queuing
    redis:
        image: butcherman/tech_bench_redis:1.0
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./appData/redis:/bitnami/redis/data
        networks:
            - app-tier

    #  Scheduler Container
    scheduler:
        container_name: scheduler
        restart: unless-stopped
        image: butcherman/tech_bench_app:dev7
        volumes:
            - assetData:/app/public
            - keystore:/app/keystore
            - ./storageData/disks:/app/storage/app/
            - ./storageData/logs/scheduler:/app/storage/logs
            - ./.env:/app/.env
        environment:
            - SERVICE=scheduler
        networks:
            - app-tier

    #  Reverb Container for Websockets
    reverb:
        container_name: reverb
        restart: unless-stopped
        image: butcherman/tech_bench_app:dev7
        volumes:
            - assetData:/app/public
            - keystore:/app/keystore
            - ./storageData/disks:/app/storage/app/
            - ./storageData/logs/reverb:/app/storage/logs
            - ./.env:/app/.env
        environment:
            - SERVICE=reverb
        networks:
            - app-tier
