################################################################################
#                                                                              #
#                                                                              #
#                          Tech Bench Docker Installation                      #
#           NOTE:  Check .env file for necessary fields to modify to           #
#                        secure this Tech Bench installation                   #
#                                                                              #
#                                                                              #
################################################################################
networks:
    app-tier:
        driver: bridge
volumes:
    appData:
    dbData:
    redisData:
    meilisearchData:

services:
    # Application Container
    tech_bench:
        container_name: tech_bench
        image: butcherman/tech_bench_app:${APP_VERSION:-latest}
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - appData:/var/www/html
            - ./.env:/var/www/html/.env
        environment:
            - SERVICE=app
        networks:
            - app-tier
        depends_on:
            database:
                condition: service_healthy

    # NGINX Web Server
    nginx:
        container_name: nginx
        image: butcherman/tech_bench_nginx:2.0
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - appData:/var/www/html
            - ./.env:/var/www/html/.env
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-tier
        depends_on:
            database:
                condition: service_started
            reverb:
                condition: service_started

    #  Reverb Container for Websockets
    reverb:
        container_name: reverb
        image: butcherman/tech_bench_app:${APP_VERSION:-latest}
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - appData:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        depends_on:
            tech_bench:
                condition: service_healthy

    #  Horizon Container to run background jobs
    horizon:
        container_name: horizon
        image: butcherman/tech_bench_app:${APP_VERSION:-latest}
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - appData:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        depends_on:
            tech_bench:
                condition: service_healthy
            nginx:
                condition: service_healthy

    #  Scheduler Container
    scheduler:
        container_name: scheduler
        image: butcherman/tech_bench_app:${APP_VERSION:-latest}
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - appData:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ["php", "/var/www/html/artisan", "schedule:work"]
        depends_on:
            tech_bench:
                condition: service_healthy
            nginx:
                condition: service_healthy

    # MySQL Database Container
    database:
        container_name: database
        image: butcherman/tech_bench_database:2.0
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - dbData:/var/lib/mysql
        networks:
            - app-tier

    #  Redis Container for Cache, Job and Email Queuing
    redis:
        container_name: redis
        image: butcherman/tech_bench_redis:2.0
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - redisData:/data
        networks:
            - app-tier

    # Melisearch Container for Search Engine
    meilisearch:
        container_name: meilisearch
        image: butcherman/tech_bench_meilisearch:1.1
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - meilisearchData:/meili_data
        networks:
            - app-tier
        depends_on:
            database:
                condition: service_healthy
