################################################################################
#                                                                              #
#                                                                              #
#                         Tech Bench Docker Development                        #
#           NOTE:  Check .env file for necessary fields to modify to           #
#                      secure this Tech Bench installation                     #
#                                                                              #
#                                                                              #
################################################################################
name: tech_bench_dev
networks:
    app-tier:
        driver: bridge
volumes:
    dbDevData:
    redisDevData:
    meilisearchDevData:
    backupData:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './backupData'

services:
    # Application Container
    tech_bench:
        container_name: tech_bench
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./tech_bench
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        environment:
            - SERVICE=app
        networks:
            - app-tier
        healthcheck:
            test: ["CMD", "php-fpm-healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 10
        depends_on:
            database:
                condition: service_healthy

    # NGINX Web Server
    nginx:
        image: butcherman/tech_bench_nginx:2.0
        container_name: nginx
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-tier
        depends_on:
            tech_bench:
                condition: service_healthy

    # Reverb Container for Websockets
    reverb:
        container_name: reverb
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./tech_bench
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ['php', '/var/www/html/artisan', 'reverb:start']
        depends_on:
            tech_bench:
                condition: service_healthy

    # Horizon Container to run background jobs
    horizon:
        container_name: horizon
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./tech_bench
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ["php", "/var/www/html/artisan", "horizon"]
        depends_on:
            tech_bench:
                condition: service_healthy

    # Scheduler Container
    scheduler:
        container_name: scheduler
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./tech_bench
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ["php", "/var/www/html/artisan", "schedule:work"]
        depends_on:
            tech_bench:
                condition: service_healthy

    # MySQL Database Container
    database:
        image: butcherman/tech_bench_database:1.0
        container_name: database
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - dbDevData:/bitnami/mysql/data
        networks:
            - app-tier
        ports:
            - "3306:3306"
        healthcheck:
            test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
            interval: 15s
            timeout: 5s
            retries: 6

    #  Redis Container for Cache, Job and Email Queuing
    redis:
        image: butcherman/tech_bench_redis:1.0
        container_name: redis
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - redisDevData:/bitnami/redis/data
        networks:
            - app-tier
        ports:
            - "6379:6379"

    # Melisearch Container for Search Engine
    meilisearch:
        image: butcherman/tech_bench_meilisearch:1.0
        container_name: meilisearch
        restart: unless-stopped
        stop_signal: SIGTERM
        volumes:
            - meilisearchDevData:/meili_data
        networks:
            - app-tier
        ports:
            - 7700:7700

    ############################################################################
    #                       Dev Specific Containers                            #
    ############################################################################

    # Mailpit for Email Traps
    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        restart: unless-stopped
        stop_signal: SIGTERM
        networks:
            - app-tier
        ports:
            - "8025:8025"
            - "1025:1025"

    # NPM Container to run npm run dev
    npm:
        container_name: npm
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./tech_bench
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        ports:
            - "5173:5173"
        command: npm run dev
        depends_on:
            tech_bench:
                condition: service_healthy
