<template>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-3 my-3">
        <Card title="Resource List">
            <ResourceList :list="resourceListData" />
        </Card>
        <Card title="Stacked Table">
            <TableStacked :items="stackedTable" class="w-full" bordered />
        </Card>
        <Card title="Data Table" class="md:col-span-2">
            <DataTable :columns="tableColumns" :rows="tableRows" />
        </Card>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Card from "../_Base/Card.vue";
import ResourceList from "../_Base/ResourceList.vue";
import TableStacked from "../_Base/TableStacked.vue";
import DataTable from "../_Base/DataTable/DataTable.vue";

const resourceListData = ref([
    {
        icon: "pencil",
        text: "List Item that is a link",
        href: route("about"),
    },
    {
        icon: "eye",
        text: "List Item with an icon",
    },
    {
        text: "Plain Text Item",
    },
    {
        text: "More Plain Text",
    },
]);

const stackedTable = ref({
    city: "Sacramento",
    state: "California",
    country: "United States",
    true_value: true,
    false_value: false,
});

const tableColumns = ref([
    {
        label: "Name",
        field: "full_name",
        filterable: true,
        sort: true,
    },
    {
        label: "Email",
        field: "email",
        filterable: false,
        sort: true,
    },
    {
        label: "Username",
        field: "username",
        icon: "user",
        sort: false,
    },
    {
        label: "User Role",
        field: "role_name",
        filterable: true,
        filterSelect: true,
    },
]);

const tableRows = ref([
    {
        email: "admin@em.com",
        first_name: "System",
        full_name: "System Administrator",
        initials: "SA",
        last_name: "Administrator",
        username: "admin",
        role_name: "Installer",
    },
    {
        email: "tech@em.com",
        first_name: "Tech",
        full_name: "Tech User",
        initials: "TU",
        last_name: "User",
        username: "tech",
        role_name: "Administrator",
    },
    {
        email: "Arthur.Grimes@noEm.com",
        first_name: "Arthur",
        full_name: "Arthur Grimes",
        initials: "AG",
        last_name: "Grimes",
        username: "Arthur.Grimes",
        role_name: "Tech",
    },
    {
        email: "Shirley.Mayer@noEm.com",
        first_name: "Shirley",
        full_name: "Shirley Mayer",
        initials: "SM",
        last_name: "Mayer",
        username: "Shirley.Mayer",
        role_name: "Reports",
    },
    {
        email: "Adrianna.Schneider@noEm.com",
        first_name: "Adrianna",
        full_name: "Adrianna Schneider",
        initials: "AS",
        last_name: "Schneider",
        username: "Adrianna.Schneider",
        role_name: "Tech",
    },
    {
        email: "Syble.Abshire@noEm.com",
        first_name: "Syble",
        full_name: "Syble Abshire",
        initials: "SA",
        last_name: "Abshire",
        username: "Syble.Abshire",
        role_name: "Tech",
    },
    {
        email: "Delia.Schuster@noEm.com",
        first_name: "Delia",
        full_name: "Delia Schuster",
        initials: "DS",
        last_name: "Schuster",
        username: "Delia.Schuster",
        role_name: "Tech",
    },
    {
        email: "Fay.Tromp@noEm.com",
        first_name: "Fay",
        full_name: "Fay Tromp",
        initials: "FT",
        last_name: "Tromp",
        username: "Fay.Tromp",
        role_name: "Tech",
    },
    {
        email: "Garth.Walker@noEm.com",
        first_name: "Garth",
        full_name: "Garth Walker",
        initials: "GW",
        last_name: "Walker",
        username: "Garth.Walker",
        role_name: "Tech",
    },
    {
        email: "Amara.Willms@noEm.com",
        first_name: "Amara",
        full_name: "Amara Willms",
        initials: "AW",
        last_name: "Willms",
        username: "Amara.Willms",
        role_name: "Tech",
    },
    {
        email: "Colby.Hagenes@noEm.com",
        first_name: "Colby",
        full_name: "Colby Hagenes",
        initials: "CH",
        last_name: "Hagenes",
        username: "Colby.Hagenes",
        role_name: "Tech",
    },
    {
        email: "Letitia.Morar@noEm.com",
        first_name: "Letitia",
        full_name: "Letitia Morar",
        initials: "LM",
        last_name: "Morar",
        username: "Letitia.Morar",
        role_name: "Administrator",
    },
    {
        email: "Harmony.Schroeder@noEm.com",
        first_name: "Harmony",
        full_name: "Harmony Schroeder",
        initials: "HS",
        last_name: "Schroeder",
        username: "Harmony.Schroeder",
        role_name: "Installer",
    },
    {
        email: "Amelia.Dicki@noEm.com",
        first_name: "Amelia",
        full_name: "Amelia Dicki",
        initials: "AD",
        last_name: "Dicki",
        username: "Amelia.Dicki",
        role_name: "Tech",
    },
    {
        email: "Cary.Haag@noEm.com",
        first_name: "Cary",
        full_name: "Cary Haag",
        initials: "CH",
        last_name: "Haag",
        username: "Cary.Haag",
        role_name: "Tech",
    },
    {
        email: "Owen.Nader@noEm.com",
        first_name: "Owen",
        full_name: "Owen Nader",
        initials: "ON",
        last_name: "Nader",
        username: "Owen.Nader",
        role_name: "Tech",
    },
    {
        email: "Daren.Nitzsche@noEm.com",
        first_name: "Daren",
        full_name: "Daren Nitzsche",
        initials: "DN",
        last_name: "Nitzsche",
        username: "Daren.Nitzsche",
        role_name: "Tech",
    },
    {
        email: "Madilyn.Torp@noEm.com",
        first_name: "Madilyn",
        full_name: "Madilyn Torp",
        initials: "MT",
        last_name: "Torp",
        username: "Madilyn.Torp",
        role_name: "Tech",
    },
    {
        email: "Janet.Kuhlman@noEm.com",
        first_name: "Janet",
        full_name: "Janet Kuhlman",
        initials: "JK",
        last_name: "Kuhlman",
        username: "Janet.Kuhlman",
        role_name: "Reports",
    },
    {
        email: "Alphonso.Witting@noEm.com",
        first_name: "Alphonso",
        full_name: "Alphonso Witting",
        initials: "AW",
        last_name: "Witting",
        username: "Alphonso.Witting",
        role_name: "Administrator",
    },
    {
        email: "Marcelino.Doyle@noEm.com",
        first_name: "Marcelino",
        full_name: "Marcelino Doyle",
        initials: "MD",
        last_name: "Doyle",
        username: "Marcelino.Doyle",
        role_name: "Tech",
    },
    {
        email: "Alfred.Russel@noEm.com",
        first_name: "Alfred",
        full_name: "Alfred Russel",
        initials: "AR",
        last_name: "Russel",
        username: "Alfred.Russel",
        role_name: "Tech",
    },
    {
        email: "Frieda.Dach@noEm.com",
        first_name: "Frieda",
        full_name: "Frieda Dach",
        initials: "FD",
        last_name: "Dach",
        username: "Frieda.Dach",
        role_name: "Tech",
    },
    {
        email: "Jadyn.Stoltenberg@noEm.com",
        first_name: "Jadyn",
        full_name: "Jadyn Stoltenberg",
        initials: "JS",
        last_name: "Stoltenberg",
        username: "Jadyn.Stoltenberg",
        role_name: "Tech",
    },
    {
        email: "Jaime.Jacobson@noEm.com",
        first_name: "Jaime",
        full_name: "Jaime Jacobson",
        initials: "JJ",
        last_name: "Jacobson",
        username: "Jaime.Jacobson",
        role_name: "Tech",
    },
    {
        email: "German.Windler@noEm.com",
        first_name: "German",
        full_name: "German Windler",
        initials: "GW",
        last_name: "Windler",
        username: "German.Windler",
        role_name: "Tech",
    },
    {
        email: "Meghan.Keeling@noEm.com",
        first_name: "Meghan",
        full_name: "Meghan Keeling",
        initials: "MK",
        last_name: "Keeling",
        username: "Meghan.Keeling",
        role_name: "Tech",
    },
    {
        email: "Wilhelm.Buckridge@noEm.com",
        first_name: "Wilhelm",
        full_name: "Wilhelm Buckridge",
        initials: "WB",
        last_name: "Buckridge",
        username: "Wilhelm.Buckridge",
        role_name: "Tech",
    },
    {
        email: "Samanta.Rice@noEm.com",
        first_name: "Samanta",
        full_name: "Samanta Rice",
        initials: "SR",
        last_name: "Rice",
        username: "Samanta.Rice",
        role_name: "Tech",
    },
    {
        email: "Nickolas.Parker@noEm.com",
        first_name: "Nickolas",
        full_name: "Nickolas Parker",
        initials: "NP",
        last_name: "Parker",
        username: "Nickolas.Parker",
        role_name: "Tech",
    },
    {
        email: "Elody.Schaden@noEm.com",
        first_name: "Elody",
        full_name: "Elody Schaden",
        initials: "ES",
        last_name: "Schaden",
        username: "Elody.Schaden",
        role_name: "Installer",
    },
    {
        email: "Harvey.Reichert@noEm.com",
        first_name: "Harvey",
        full_name: "Harvey Reichert",
        initials: "HR",
        last_name: "Reichert",
        username: "Harvey.Reichert",
        role_name: "Tech",
    },
    {
        email: "Abner.Daniel@noEm.com",
        first_name: "Abner",
        full_name: "Abner Daniel",
        initials: "AD",
        last_name: "Daniel",
        username: "Abner.Daniel",
        role_name: "Tech",
    },
    {
        email: "Elouise.Nolan@noEm.com",
        first_name: "Elouise",
        full_name: "Elouise Nolan",
        initials: "EN",
        last_name: "Nolan",
        username: "Elouise.Nolan",
        role_name: "Tech",
    },
    {
        email: "Ewald.Nikolaus@noEm.com",
        first_name: "Ewald",
        full_name: "Ewald Nikolaus",
        initials: "EN",
        last_name: "Nikolaus",
        username: "Ewald.Nikolaus",
        role_name: "Tech",
    },
    {
        email: "Kolby.Reichert@noEm.com",
        first_name: "Kolby",
        full_name: "Kolby Reichert",
        initials: "KR",
        last_name: "Reichert",
        username: "Kolby.Reichert",
        role_name: "Tech",
    },
    {
        email: "Eudora.Sauer@noEm.com",
        first_name: "Eudora",
        full_name: "Eudora Sauer",
        initials: "ES",
        last_name: "Sauer",
        username: "Eudora.Sauer",
        role_name: "Tech",
    },
    {
        email: "Alexis.Green@noEm.com",
        first_name: "Alexis",
        full_name: "Alexis Green",
        initials: "AG",
        last_name: "Green",
        username: "Alexis.Green",
        role_name: "Tech",
    },
    {
        email: "Tom.Lang@noEm.com",
        first_name: "Tom",
        full_name: "Tom Lang",
        initials: "TL",
        last_name: "Lang",
        username: "Tom.Lang",
        role_name: "Tech",
    },
    {
        email: "Sven.Willms@noEm.com",
        first_name: "Sven",
        full_name: "Sven Willms",
        initials: "SW",
        last_name: "Willms",
        username: "Sven.Willms",
        role_name: "Tech",
    },
    {
        email: "Demario.Kihn@noEm.com",
        first_name: "Demario",
        full_name: "Demario Kihn",
        initials: "DK",
        last_name: "Kihn",
        username: "Demario.Kihn",
        role_name: "Tech",
    },
    {
        email: "Lavina.Reichert@noEm.com",
        first_name: "Lavina",
        full_name: "Lavina Reichert",
        initials: "LR",
        last_name: "Reichert",
        username: "Lavina.Reichert",
        role_name: "Tech",
    },
    {
        email: "Porter.Jacobi@noEm.com",
        first_name: "Porter",
        full_name: "Porter Jacobi",
        initials: "PJ",
        last_name: "Jacobi",
        username: "Porter.Jacobi",
        role_name: "Tech",
    },
    {
        email: "Emil.Fahey@noEm.com",
        first_name: "Emil",
        full_name: "Emil Fahey",
        initials: "EF",
        last_name: "Fahey",
        username: "Emil.Fahey",
        role_name: "Tech",
    },
    {
        email: "Melisa.Roberts@noEm.com",
        first_name: "Melisa",
        full_name: "Melisa Roberts",
        initials: "MR",
        last_name: "Roberts",
        username: "Melisa.Roberts",
        role_name: "Tech",
    },
    {
        email: "Lynn.Farrell@noEm.com",
        first_name: "Lynn",
        full_name: "Lynn Farrell",
        initials: "LF",
        last_name: "Farrell",
        username: "Lynn.Farrell",
        role_name: "Tech",
    },
    {
        email: "Audie.Hills@noEm.com",
        first_name: "Audie",
        full_name: "Audie Hills",
        initials: "AH",
        last_name: "Hills",
        username: "Audie.Hills",
        role_name: "Tech",
    },
    {
        email: "Ima.VonRueden@noEm.com",
        first_name: "Ima",
        full_name: "Ima VonRueden",
        initials: "IV",
        last_name: "VonRueden",
        username: "Ima.VonRueden",
        role_name: "Tech",
    },
]);
</script>
