<template>
    <VueForm
        ref="backupForm"
        :initial-values="initValues"
        :validation-schema="schema"
        submit-text="Update Backup Settings"
        @submit="onSubmit"
    >
        <CheckboxSwitch
            id="enable-auto"
            name="nightly_backup"
            label="Enable Nightly Updates"
            help="When enabled, backups will run nightly at 03:00"
        />
        <CheckboxSwitch
            id="enable-cleanup"
            name="nightly_cleanup"
            label="Enable Auto Backup Cleanup"
            help="When enabled, backups will be kept based on the cleanup schedule noted below.  When disabled, all backups are kept regardless of age."
        />
        <CheckboxSwitch
            id="encryption"
            name="encryption"
            label="Encrypt Backup"
            help="When enabled, backups are password protected"
        />
        <TextInput
            id="password"
            name="password"
            label="Encryption Password"
            type="password"
            :disabled="!backupForm?.getFieldValue('encryption')"
        />
        <TextInput
            id="email"
            name="mail_to"
            label="Email Notifications To"
            type="email"
            help="Any notifications generated by the backup process will be sent to this email address"
        />
    </VueForm>
</template>

<script setup lang="ts">
import VueForm from "@/Forms/_Base/VueForm.vue";
import TextInput from "@/Forms/_Base/TextInput.vue";
import CheckboxSwitch from "@/Forms/_Base/CheckboxSwitch.vue";
import { ref } from "vue";
import { object, string, boolean } from "yup";
import { useForm } from "@inertiajs/vue3";

const props = defineProps<{
    backupSettings: backupSettings;
}>();

const backupForm = ref<InstanceType<typeof VueForm> | null>(null);
const initValues = {
    nightly_backup: props.backupSettings.nightly_backup,
    nightly_cleanup: props.backupSettings.nightly_cleanup,
    encryption: props.backupSettings.encryption,
    password: props.backupSettings.password,
    mail_to: props.backupSettings.mail_to,
};
const schema = object({
    nightly_backup: boolean().required(),
    nightly_cleanup: boolean().required(),
    encryption: boolean().required(),
    password: string().when("encryption", {
        is: true,
        then: (schema) => schema.required(),
        otherwise: (schema) => schema.nullable(),
    }),
    mail_to: string().email().required(),
});

const onSubmit = (form: backupSettings) => {
    const formData = useForm(form);

    formData.post(route("admin.backups.settings.set"), {
        onFinish: () => backupForm.value?.endSubmit(),
    });
};
</script>
