#  This file contains the default .env file for production environments
echo "APP_KEY=" > .env
echo "APP_URL=\"$WEB_URL\"" >> .env
echo '' >> .env
echo 'TIMEZONE="America/Los_Angeles"' >> .env
echo '' >> .env
echo "DB_CONNECTION=mysql" >> .env
echo "DB_HOST=127.0.0.1" >> .env
echo "DB_PORT=3306" >> .env
echo "DB_DATABASE=\"$DBNAME\"" >> .env
echo "DB_USERNAME=\"$NEWUSER\"" >> .env
echo "DB_PASSWORD=\"$NEWPASS\"" >> .env
echo '' >> .env
echo "MAIL_DRIVER=smtp" >> .env
echo "MAIL_HOST=smtp.mailtrap.io" >> .env
echo "MAIL_PORT=2525" >> .env
echo "MAIL_USERNAME=null" >> .env
echo "MAIL_PASSWORD=null" >> .env
echo "MAIL_ENCRYPTION=null" >> .env
echo "MAIL_FROM_ADDRESS=null" >> .env
echo 'MAIL_FROM_NAME="Tech Bench"' >> .env
echo '' >> .env
echo '#DFLT_FOLDER="\default"' >> .env
echo '#SYS_FOLDER="\systems"' >> .env
echo '#CUST_FOLDER="\customers"' >> .env
echo '#USER_FOLDER="\users"' >> .env
echo '#TIP_FOLDER="\tips"' >> .env
echo '#LINK_FOLDER="\links"' >> .env
echo '#COMP_FOLDER="\company"' >> .env
echo '#MAX_UPLOAD=2147483648' >> .env
echo '' >> .env
