################################################################################
#                                                                              #
#      Meilisearch Container is the Search Engine for Tech Bench               #
#                                                                              #
################################################################################

FROM getmeili/meilisearch:v1.9.0

ENV MEILI_ENV=production
ENV MEILI_MASTER_KEY=TechBenchMeilisearchMasterKey

